###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '5556:8025'

    redis:
        image: 'redis:alpine'

    mysql:
        image: 'mysql:8.0'
        working_dir: /home/singurix/www/laravel
        volumes:
            - '.:/home/singurix/www/laravel'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel-user
            - MYSQL_PASSWORD=laravel-password
        ports:
            - '5557:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /home/singurix/www/laravel
        volumes:
            - '.:/home/singurix/www/laravel'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '5555:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /home/singurix/www/laravel
        volumes:
            - '.:/home/singurix/www/laravel'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
